# Generated by Django 6.1.1 on 2026-09-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ('tartib', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180, verbose_name='Nomi')),
                ('tavsif', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ('tartib', 'nom'),
            },
        ),
    ]
